### ISSUE TITLE
Allow all duplicate resolutions (Standard + HiDPI)

### ISSUE THREAD

**Issue by pryley** [ramiroaraujo/alfred-set-resolution-workflow#1]
> It filter's out duplicated resolutions where a retina resolution is available, for example, if you have available 1280x960 in both retina and non-retina, you'll only see the retina option; no need to set the pixelated one.

Actually, it's very handy to have the pixelated resolution available to toggle to when you are a front-end web developer. When coding css for a site, you are serving different images depending on the DPI so it's handy to toggle HiDPI resolutions to test the CSS. http://www.sitepoint.com/css-techniques-for-retina-displays/

**Comment by ramiroaraujo** [comment]
Hmm, I see your point, as I'm a web developer myself :)
But it was so naggy when all the possible resolutions populated, there're really quite a few. I'll see if If I add it as a config option. In the meanwhile, you can comment in workflow_config.rb from lines 92 to 97 to disable the filter.

Cheers

**Comment by wolph** [comment]
A better solution might be to use modifier keys, just make cmd+enter change to the low-DPI version and make the normal one use the high-DPI version.

Alternatively, you could even just have a HiDPI switch instead of showing them double.

**Comment by ramiroaraujo** [comment]
nice one. I have a pending task of rewriting most of my plugins from Ruby
to PHP. The Ruby version diff from previous versions is a hazard to
maintain, and I need to keep supporting mountain lion for example, since
many co-workers are still stuck with it :(. I'll leave that change for
after that, or you could PR it :)

## 

Ramiro Araujo

**Comment by wolph** [comment]
Perhaps you should try Python instead, it's very similar to Ruby in terms of writing it and has a very stable API. If you write code for Python 2.4 (which came out over 10 years ago) it still functions in Python 2.7.9 (which came out 4 months ago). And with a few modifications you can even future-proof it easily so it works with Python 3.x as well.
